TAG: 'mile'
LOG_DIR: 'tensorboard_logs'

GPUS: 1
BATCHSIZE: 4
STEPS: 100000

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 8

RECEPTIVE_FIELD: 1
FUTURE_HORIZON: 0

PRETRAINED:
  PATH: '/home/ps/dujiatong/transfer-mile-0114/tensorboard_logs/14January2025at22:30:10CST_ps_mile/epoch=4-step=41500.ckpt'

DATASET:
  DATAROOT: ''
